export const jobs = [
  {
    company: "Scotiabank",
    title: "Software Engineer",
    date: "June 2023 - Present",
    location: "Toronto, Canada",
    link: "https://www.scotiabank.com/ca/en/personal.html",
    description: [
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quae.",
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quae.",
    ],
    skills: [
      "TypeScript",
      "React",
      "Node.js",
      "GraphQL",
      "Next.js",
      "Tailwind CSS",
      "Jest",
      "Cypress",
      "Testing Library",
    ],
  },
  {
    company: "abc",
    title: "Software Engineer",
    date: "June 2023 - June 2023",
    location: "Toronto, Canada",
    link: "https://www.scotiabank.com/ca/en/personal.html",
    description: [
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quae.",
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quae.",
    ],
    skills: [
      "TypeScript",
      "React",
      "Node.js",
      "GraphQL",
      "Next.js",
      "Tailwind CSS",
      "Jest",
      "Cypress",
      "Testing Library",
    ],
  },
  {
    company: "xyz",
    title: "Software Engineer",
    date: "June 2023 - June 2023",
    location: "Toronto, Canada",
    link: "https://www.scotiabank.com/ca/en/personal.html",
    description: [
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quae.",
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quae.",
    ],
    skills: [
      "TypeScript",
      "React",
      "Node.js",
      "GraphQL",
      "Next.js",
      "Tailwind CSS",
      "Jest",
      "Cypress",
      "Testing Library",
    ],
  },
] as const;
